gem 'sinatra'
gem 'sinatra-static-assets', :require_as => 'sinatra/static_assets'
gem 'rack-flash', :require_as => 'rack/flash'
gem 'extlib'
gem 'haml'
gem 'bcrypt-ruby', "2.0.5", :require_as => 'bcrypt'
gem 'warden'
gem 'sinatra_warden'
gem 'haml'
gem 'sqlite3-ruby'
gem 'data_objects'
gem 'dm-core'
gem 'dm-types'
gem 'dm-validations'
gem 'do_sqlite3'
gem 'thor', "0.12.3", :require_as => 'thor'
