source :gemcutter

gem 'sinatra'
gem 'sinatra-static-assets', :require => 'sinatra/static_assets'
gem 'rack-flash', :require => 'rack/flash'
gem 'extlib'
gem 'haml'
gem 'bcrypt-ruby', "2.0.5", :require => 'bcrypt'
gem 'warden'
gem 'sinatra_warden'
gem 'haml'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'data_objects'
gem 'dm-core'
gem 'dm-types'
gem 'dm-validations'
gem 'do_sqlite3'
gem 'thor', "0.12.3", :require => 'thor'
gem 'simple-daemon'
